sudo: false
language: node_js
node_js:
  - '8'
  - '9'
install:
  - make travis-install
  - npm i npminstall && npminstall
script:
  - make travis-run
  - npm run ci
after_script:
  - npminstall codecov && codecov
  - make travis-stop
services:
  - redis-server
