sudo: false
language: node_js
node_js:
  - '8'
  - '9'
install:
  - npm i npminstall && npminstall
  - make travis-install
script:
  - npm run ci
  - make travis-run
after_script:
  - npminstall codecov && codecov
services:
  - redis-server
